
DROP FUNCTION FN_GR05_Date_Control;
DROP TRIGGER TR_GR05_COMENTARIO_Date_Control ON GR05_COMENTARIO;
DROP FUNCTION FN_GR05_Date_Control_Day;
DROP TRIGGER TR_GR05_Date_Control_Day ON GR05_COMENTARIO;
DROP FUNCTION FN_GR05_Vote_Control;
DROP TRIGGER TR_GR05_Vote_Control ON GR05_RECOMENDACION;
DROP FUNCTION FN_G05_CONTROL_GAME_COMENT;
DROP TRIGGER TR_GR05_CONTROL_GAME_COMENT ON GR05_COMENTARIO;
DROP FUNCTION FN_GR05_SYNCHRONIZATION_COMENT;
DROP TRIGGER TR_GR05_SYNCHRONIZATION_COMENT ON GR05_COMENTARIO;
DROP FUNCTION FN_G05_MAIL_PATTERN;

DROP VIEW GR05_LAST_COMENT_MONTH;
DROP VIEW GR05_LIST_USER_LAST_YEAR;
DROP VIEW GR05_MOST_20_PLAYED_GAMES;
DROP VIEW GR05_MOST_10_GAME;

DROP TABLE GR05_COMENTARIO CASCADE;
DROP TABLE GR05_COMENTA CASCADE;
DROP TABLE GR05_USUARIO CASCADE;
DROP TABLE GR05_JUEGO CASCADE;
DROP TABLE GR05_JUEGA CASCADE;
DROP TABLE GR05_CATEGORIA CASCADE;
DROP TABLE GR05_VOTO CASCADE;
DROP TABLE GR05_NIVEL CASCADE;
DROP TABLE GR05_RECOMENDACION CASCADE;
DROP TABLE GR05_TIPO_USUARIO CASCADE;